server:
  port: 16379
#redis基础配置
spring:
  application:
    name: henuqin-redis
  boot:
    admin:
      client:
        url: http://127.0.0.1:16926
  redis:
    database: 0
    host: 42.192.131.140
    port: 7963
    password:
    timeout: 3000
    #Lettuce集成
    lettuce:
      #是否使用Lettuce
      enable: false
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        #连接池中的最大空闲连接 默认 8
        max-idle: 8
        #连接池中的最小空闲连接 默认 0
        min-idle: 0
    jedis:
      #是否使用Jedis
      enable: true
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#添加开启admin的日志监控
logging:
  file:
    name: henuqin-redis-admin-client.log