server:
  port: 16928
#基础配置
spring:
  application:
    name: henuqin-es

#添加开启admin的日志监控
logging:
  file:
    name: henuqin-es.log

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:16926/eureka