server:
  port: 16927
#redis基础配置
spring:
  application:
    name: henuqin-cache
  redis:
    database: 0
    host: 42.192.131.140
    port: 7963
    password:
    timeout: 3000
    #Lettuce集成
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        #连接池中的最大空闲连接 默认 8
        max-idle: 8
        #连接池中的最小空闲连接 默认 0
        min-idle: 0
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:16926/eureka